/* ============================================================
   MAHR FRAGRANCES — Product Database
   Structured per Phase 7: Product Database & Metafield Architecture
   ============================================================ */

const MAHR_PRODUCTS = [
  {
    id: "mahr-noir",
    sku: "MAHR-NOIR",
    name: "MAHR NOIR",
    tagline: "Elegant. Confident. Mysterious.",
    gender: "unisex",
    family: "woody-oriental",
    familyLabel: "Woody Oriental",
    collectionTags: ["unisex", "arabic-luxury", "best-sellers"],
    notes: { top: ["Bergamot", "Pink Pepper"], middle: ["Rose", "Spices"], base: ["Oud", "Amber", "Musk"] },
    performance: { longevity: "8+ Hours", projection: "Strong", sillage: "Noticeable", bestTime: "Evening" },
    occasion: ["Evening", "Wedding", "Special Events"],
    season: ["Winter", "Monsoon", "All Season"],
    personality: ["Elegant", "Confident", "Mysterious"],
    mood: "Mysterious",
    badges: ["Bestseller", "Signature"],
    price: { "30ml": 799, "50ml": 1499, "100ml": 2499 },
    rating: 4.8,
    reviewCount: 46,
    colorway: "arabic",
    inspiration: "Created around the character of iconic Arabian oud houses — deep, resinous, and unmistakably confident.",
    story: "MAHR NOIR was built for the moment a room goes quiet when you walk in. It opens with a flash of pepper and citrus before settling into a heart of rose and warm spice, finishing on a base that lingers for hours — oud, amber, and musk layered like velvet.",
    craftsmanship: "Blended in small batches using food-grade alcohol and imported oud accords, then rested for four weeks before bottling to let the notes marry.",
    isNew: false,
    isBestseller: true
  },
  {
    id: "mahr-oud-royal",
    sku: "MAHR-OUDROYAL",
    name: "MAHR OUD ROYAL",
    tagline: "Rich. Warm. Timeless.",
    gender: "unisex",
    family: "oud",
    familyLabel: "Oud",
    collectionTags: ["unisex", "arabic-luxury", "best-sellers", "gifts"],
    notes: { top: ["Saffron", "Cardamom"], middle: ["Rose", "Oud Wood"], base: ["Oud", "Sandalwood", "Amber"] },
    performance: { longevity: "8+ Hours", projection: "Very Strong", sillage: "Strong", bestTime: "Night" },
    occasion: ["Wedding", "Eid", "Special Events"],
    season: ["Winter", "All Season"],
    personality: ["Bold", "Luxurious", "Mysterious"],
    mood: "Luxury",
    badges: ["Bestseller"],
    price: { "30ml": 899, "50ml": 1699, "100ml": 2499 },
    rating: 4.9,
    reviewCount: 63,
    colorway: "arabic",
    inspiration: "Inspired by the character of pure Arabian oud traditions — smoky, precious, and deeply rooted in heritage.",
    story: "A tribute to the oud houses of the Gulf, MAHR OUD ROYAL leads with saffron and cardamom before revealing a heart of rose over aged oud wood. It's the fragrance for weddings, Eid mornings, and every occasion that calls for reverence.",
    craftsmanship: "Sourced oud accords blended with cold-pressed sandalwood for a smoother, rounder smoke than raw oud alone.",
    isNew: false,
    isBestseller: true
  },
  {
    id: "mahr-asad-noir",
    sku: "MAHR-ASADNOIR",
    name: "MAHR ASAD NOIR",
    tagline: "Powerful. Grounded. Unshaken.",
    gender: "men",
    family: "woody",
    familyLabel: "Woody Leather",
    collectionTags: ["for-him", "arabic-luxury"],
    notes: { top: ["Black Pepper", "Bergamot"], middle: ["Leather", "Cedar"], base: ["Oud", "Vetiver", "Musk"] },
    performance: { longevity: "6-8 Hours", projection: "Strong", sillage: "Moderate", bestTime: "Evening" },
    occasion: ["Office", "Date Night", "Special Events"],
    season: ["Winter", "Monsoon"],
    personality: ["Bold", "Confident"],
    mood: "Powerful",
    badges: ["Signature"],
    price: { "30ml": 799, "50ml": 1499, "100ml": 2399 },
    rating: 4.7,
    reviewCount: 29,
    colorway: "him",
    inspiration: "Created around the character of the modern Arabian gentleman — sharp tailoring, quiet strength.",
    story: "Named for the lion (Asad), this fragrance opens sharp and settles into leather and cedar with a smoky oud base. Wear it to the boardroom or the ballroom — it holds its shape either way.",
    craftsmanship: "A dry-down built on vetiver and cedar oil for a fragrance that reads more like a tailored jacket than a cologne.",
    isNew: false,
    isBestseller: false
  },
  {
    id: "mahr-bleu-signature",
    sku: "MAHR-BLEUSIG",
    name: "MAHR BLEU SIGNATURE",
    tagline: "Clean. Sharp. Reliable.",
    gender: "men",
    family: "aquatic",
    familyLabel: "Fresh Aquatic",
    collectionTags: ["for-him", "fresh"],
    notes: { top: ["Grapefruit", "Sea Salt"], middle: ["Lavender", "Geranium"], base: ["Musk", "Ambroxan"] },
    performance: { longevity: "6-8 Hours", projection: "Moderate", sillage: "Moderate", bestTime: "Day" },
    occasion: ["Daily Wear", "Office"],
    season: ["Summer", "All Season"],
    personality: ["Fresh", "Calm"],
    mood: "Refreshing",
    badges: [],
    price: { "30ml": 749, "50ml": 1399, "100ml": 2299 },
    rating: 4.6,
    reviewCount: 34,
    colorway: "him",
    inspiration: "Inspired by iconic fresh-aquatic profiles built for daily, dependable wear.",
    story: "MAHR BLEU SIGNATURE is the fragrance you reach for without thinking — grapefruit and sea salt up top, a soft lavender heart, and a musk base clean enough for the office and warm enough for dinner after.",
    craftsmanship: "Formulated with ambroxan for a long-wearing, skin-close finish rather than a loud, synthetic marine note.",
    isNew: false,
    isBestseller: false
  },
  {
    id: "mahr-ocean-breeze",
    sku: "MAHR-OCEANBRZ",
    name: "MAHR OCEAN BREEZE",
    tagline: "Bright. Airy. Effortless.",
    gender: "men",
    family: "aquatic",
    familyLabel: "Fresh Aquatic",
    collectionTags: ["for-him", "fresh"],
    notes: { top: ["Bergamot", "Marine Accord"], middle: ["Water Lily", "Cardamom"], base: ["Cedar", "Musk"] },
    performance: { longevity: "4-6 Hours", projection: "Moderate", sillage: "Close", bestTime: "Day" },
    occasion: ["Daily Wear", "Travel"],
    season: ["Summer", "Monsoon"],
    personality: ["Fresh", "Calm"],
    mood: "Energetic",
    badges: ["New"],
    price: { "30ml": 749, "50ml": 1399, "100ml": 2199 },
    rating: 4.5,
    reviewCount: 12,
    colorway: "him",
    inspiration: "Inspired by the feeling of coastal mornings — light, clean, unhurried.",
    story: "A newer addition built for humid days and long commutes. Marine accord and bergamot up front, cedar underneath to keep it grounded.",
    craftsmanship: "Lower alcohol concentration for a lighter, more transparent trail suited to warm climates.",
    isNew: true,
    isBestseller: false
  },
  {
    id: "mahr-verde-essence",
    sku: "MAHR-VERDEESS",
    name: "MAHR VERDE ESSENCE",
    tagline: "Earthy. Composed. Enduring.",
    gender: "men",
    family: "woody",
    familyLabel: "Woody",
    collectionTags: ["for-him"],
    notes: { top: ["Green Apple", "Basil"], middle: ["Vetiver", "Fig"], base: ["Sandalwood", "Oakmoss"] },
    performance: { longevity: "6-8 Hours", projection: "Moderate", sillage: "Moderate", bestTime: "Day" },
    occasion: ["Office", "Daily Wear"],
    season: ["All Season"],
    personality: ["Calm", "Elegant"],
    mood: "Relaxed",
    badges: [],
    price: { "30ml": 799, "50ml": 1499, "100ml": 2399 },
    rating: 4.4,
    reviewCount: 18,
    colorway: "him",
    inspiration: "Created around the character of quiet, green woody profiles favoured for understated confidence.",
    story: "Green and grounded — a fig and vetiver heart over sandalwood, built for the person who'd rather be memorable than loud.",
    craftsmanship: "Oakmoss base sourced for its natural, forest-floor depth rather than a synthetic woody accord.",
    isNew: false,
    isBestseller: false
  },
  {
    id: "mahr-amber-gold",
    sku: "MAHR-AMBERGLD",
    name: "MAHR AMBER GOLD",
    tagline: "Warm. Spiced. Magnetic.",
    gender: "men",
    family: "oriental",
    familyLabel: "Oriental Spicy",
    collectionTags: ["for-him", "arabic-luxury"],
    notes: { top: ["Cinnamon", "Orange"], middle: ["Amber", "Clove"], base: ["Vanilla", "Tonka Bean"] },
    performance: { longevity: "8+ Hours", projection: "Strong", sillage: "Noticeable", bestTime: "Evening" },
    occasion: ["Date Night", "Special Events"],
    season: ["Winter"],
    personality: ["Warm", "Bold"],
    mood: "Warm",
    badges: ["Signature"],
    price: { "30ml": 849, "50ml": 1599, "100ml": 2499 },
    rating: 4.7,
    reviewCount: 27,
    colorway: "him",
    inspiration: "Inspired by iconic amber-spice fragrance profiles built for cold-weather evenings.",
    story: "Cinnamon and orange give way to amber and clove, before a tonka-vanilla base that reads warm without tipping sweet.",
    craftsmanship: "Tonka bean absolute used for a rounder, less sugary sweetness than vanillin alone.",
    isNew: false,
    isBestseller: false
  },
  {
    id: "mahr-rose-noir",
    sku: "MAHR-ROSENOIR",
    name: "MAHR ROSE NOIR",
    tagline: "Feminine. Graceful. Luxurious.",
    gender: "women",
    family: "floral",
    familyLabel: "Floral",
    collectionTags: ["for-her", "best-sellers"],
    notes: { top: ["Pink Pepper", "Bergamot"], middle: ["Rose", "Peony"], base: ["Musk", "Amber", "Vanilla"] },
    performance: { longevity: "6-8 Hours", projection: "Moderate", sillage: "Moderate", bestTime: "Evening" },
    occasion: ["Date Night", "Wedding", "Special Events"],
    season: ["All Season"],
    personality: ["Elegant", "Romantic"],
    mood: "Luxury",
    badges: ["Bestseller"],
    price: { "30ml": 799, "50ml": 1499, "100ml": 2499 },
    rating: 4.9,
    reviewCount: 58,
    colorway: "her",
    inspiration: "Created around the character of modern rose-forward luxury fragrances.",
    story: "A rose built for evenings — pink pepper and bergamot open into peony and rose at the heart, resting on musk, amber and a whisper of vanilla.",
    craftsmanship: "Bulgarian rose absolute blended with peony for a fresher, less powdery rose accord.",
    isNew: false,
    isBestseller: true
  },
  {
    id: "mahr-velvet-rose",
    sku: "MAHR-VELVETROSE",
    name: "MAHR VELVET ROSE",
    tagline: "Soft. Sweet. Inviting.",
    gender: "women",
    family: "gourmand",
    familyLabel: "Floral Gourmand",
    collectionTags: ["for-her", "gifts"],
    notes: { top: ["Raspberry", "Bergamot"], middle: ["Rose", "Praline"], base: ["Vanilla", "Musk", "Cashmeran"] },
    performance: { longevity: "6-8 Hours", projection: "Moderate", sillage: "Moderate", bestTime: "Evening" },
    occasion: ["Date Night", "Gift"],
    season: ["Winter", "Monsoon"],
    personality: ["Romantic", "Elegant"],
    mood: "Warm",
    badges: [],
    price: { "30ml": 799, "50ml": 1499, "100ml": 2399 },
    rating: 4.6,
    reviewCount: 22,
    colorway: "her",
    inspiration: "Inspired by iconic sweet-floral gourmand profiles designed for romantic occasions.",
    story: "Raspberry and rose over a praline heart, finished with soft cashmeran musk — an easy fragrance to fall for and just as easy to gift.",
    craftsmanship: "Praline accord built from tonka and hazelnut notes rather than straight gourmand sugar.",
    isNew: false,
    isBestseller: false
  },
  {
    id: "mahr-adore",
    sku: "MAHR-ADORE",
    name: "MAHR ADORE",
    tagline: "Bright. Joyful. Feminine.",
    gender: "women",
    family: "floral",
    familyLabel: "Floral",
    collectionTags: ["for-her"],
    notes: { top: ["Mandarin", "Pear"], middle: ["Jasmine", "Orange Blossom"], base: ["White Musk", "Sandalwood"] },
    performance: { longevity: "4-6 Hours", projection: "Moderate", sillage: "Close", bestTime: "Day" },
    occasion: ["Daily Wear", "Office"],
    season: ["Summer", "All Season"],
    personality: ["Fresh", "Elegant"],
    mood: "Refreshing",
    badges: ["New"],
    price: { "30ml": 749, "50ml": 1399, "100ml": 2299 },
    rating: 4.5,
    reviewCount: 9,
    colorway: "her",
    inspiration: "Inspired by iconic bright floral profiles worn daily by fragrance enthusiasts.",
    story: "Mandarin and pear open into jasmine and orange blossom — a daily floral for someone who wants elegance before 9am.",
    craftsmanship: "White musk base kept light to layer cleanly under office wear.",
    isNew: true,
    isBestseller: false
  },
  {
    id: "mahr-pure-musk",
    sku: "MAHR-PUREMUSK",
    name: "MAHR PURE MUSK",
    tagline: "Modern. Minimal. Timeless.",
    gender: "unisex",
    family: "musk",
    familyLabel: "Musk Woody",
    collectionTags: ["unisex", "best-sellers"],
    notes: { top: ["White Tea", "Bergamot"], middle: ["Iris", "Cedar"], base: ["White Musk", "Sandalwood"] },
    performance: { longevity: "6-8 Hours", projection: "Soft", sillage: "Close", bestTime: "Day" },
    occasion: ["Daily Wear", "Office"],
    season: ["All Season"],
    personality: ["Calm", "Elegant"],
    mood: "Relaxed",
    badges: ["Signature"],
    price: { "30ml": 799, "50ml": 1499, "100ml": 2399 },
    rating: 4.7,
    reviewCount: 41,
    colorway: "unisex",
    inspiration: "Created around the character of clean, skin-close musk fragrances worn by both men and women.",
    story: "A quiet fragrance built to be noticed up close — white tea and bergamot over iris and cedar, resting on the softest musk in the MAHR line.",
    craftsmanship: "Formulated with a high musk-to-alcohol ratio for longevity without volume — ideal for shared or minimalist wardrobes.",
    isNew: false,
    isBestseller: true
  },
  {
    id: "mahr-honey-amber",
    sku: "MAHR-HONEYAMBER",
    name: "MAHR HONEY AMBER",
    tagline: "Sweet. Golden. Indulgent.",
    gender: "unisex",
    family: "gourmand",
    familyLabel: "Gourmand Oriental",
    collectionTags: ["unisex", "arabic-luxury", "gifts"],
    notes: { top: ["Saffron", "Date"], middle: ["Honey", "Rose"], base: ["Amber", "Oud", "Vanilla"] },
    performance: { longevity: "8+ Hours", projection: "Strong", sillage: "Strong", bestTime: "Night" },
    occasion: ["Party", "Wedding", "Gift"],
    season: ["Winter", "All Season"],
    personality: ["Bold", "Warm"],
    mood: "Luxury",
    badges: [],
    price: { "30ml": 849, "50ml": 1599, "100ml": 2499 },
    rating: 4.8,
    reviewCount: 31,
    colorway: "arabic",
    inspiration: "Inspired by the character of golden Arabian gourmand-oriental fragrances built for celebration.",
    story: "Saffron and date open the story, honey and rose carry it, and a base of amber, oud and vanilla makes it last well past midnight.",
    craftsmanship: "Real honey absolute blended into the amber base for a rounder sweetness than sugar-forward gourmands.",
    isNew: false,
    isBestseller: false
  },
  {
    id: "mahr-saffron-nights",
    sku: "MAHR-SAFFRONNIGHTS",
    name: "MAHR SAFFRON NIGHTS",
    tagline: "Spiced. Nocturnal. Unforgettable.",
    gender: "unisex",
    family: "oud",
    familyLabel: "Oud Spicy",
    collectionTags: ["unisex", "arabic-luxury"],
    notes: { top: ["Saffron", "Black Pepper"], middle: ["Rose", "Incense"], base: ["Oud", "Leather", "Musk"] },
    performance: { longevity: "8+ Hours", projection: "Very Strong", sillage: "Strong", bestTime: "Night" },
    occasion: ["Party", "Special Events"],
    season: ["Winter", "Monsoon"],
    personality: ["Bold", "Mysterious"],
    mood: "Powerful",
    badges: ["New"],
    price: { "30ml": 899, "50ml": 1699, "100ml": 2499 },
    rating: 4.6,
    reviewCount: 7,
    colorway: "arabic",
    inspiration: "Inspired by iconic spiced-oud profiles favoured for after-dark occasions.",
    story: "The newest MAHR release — saffron and pepper over incense and rose, landing on oud, leather and musk. Built for parties that go past midnight.",
    craftsmanship: "Incense resin sourced and cold-infused to preserve its smoky top note through the full wear cycle.",
    isNew: true,
    isBestseller: false
  },
  {
    id: "mahr-jasmine-veil",
    sku: "MAHR-JASMINEVEIL",
    name: "MAHR JASMINE VEIL",
    tagline: "Delicate. Radiant. Romantic.",
    gender: "women",
    family: "floral",
    familyLabel: "Floral",
    collectionTags: ["for-her", "gifts"],
    notes: { top: ["Litchi", "Bergamot"], middle: ["Jasmine", "Tuberose"], base: ["Sandalwood", "White Musk"] },
    performance: { longevity: "6-8 Hours", projection: "Moderate", sillage: "Moderate", bestTime: "Evening" },
    occasion: ["Date Night", "Wedding"],
    season: ["Summer", "All Season"],
    personality: ["Romantic", "Elegant"],
    mood: "Romantic",
    badges: [],
    price: { "30ml": 799, "50ml": 1499, "100ml": 2399 },
    rating: 4.7,
    reviewCount: 19,
    colorway: "her",
    inspiration: "Created around the character of radiant white-floral fragrances built for evening romance.",
    story: "Litchi and bergamot lead into a full jasmine-tuberose heart, veiled in sandalwood and musk — soft enough for a first date, memorable enough for a wedding.",
    craftsmanship: "Sambac jasmine absolute for a warmer, less sharp white floral than synthetic jasmine bases.",
    isNew: false,
    isBestseller: false
  }
];

/* ---------- Reference data (drawn from Phase 5 / Collection Architecture doc) ---------- */

const FILTER_OPTIONS = {
  gender: [
    { value: "men", label: "For Him" },
    { value: "women", label: "For Her" },
    { value: "unisex", label: "Unisex" }
  ],
  family: [
    { value: "fresh", label: "Fresh" },
    { value: "aquatic", label: "Aquatic" },
    { value: "woody", label: "Woody" },
    { value: "woody-oriental", label: "Woody Oriental" },
    { value: "oud", label: "Oud" },
    { value: "floral", label: "Floral" },
    { value: "gourmand", label: "Gourmand" },
    { value: "oriental", label: "Oriental" },
    { value: "musk", label: "Musk" }
  ],
  notes: ["Oud", "Vanilla", "Musk", "Amber", "Sandalwood", "Rose", "Jasmine", "Citrus", "Leather", "Saffron"],
  occasion: ["Daily Wear", "Office", "Date Night", "Wedding", "Party", "Special Events", "Gift", "Travel"],
  season: ["Summer", "Monsoon", "Winter", "All Season"]
};

const COLLECTIONS_META = {
  "for-him": { title: "For Him", subtitle: "Masculine. Elegant. Bold.", colorway: "him" },
  "for-her": { title: "For Her", subtitle: "Feminine. Graceful. Luxurious.", colorway: "her" },
  "unisex": { title: "Unisex Signature", subtitle: "Modern. Minimal. Timeless.", colorway: "unisex" },
  "arabic-luxury": { title: "Arabic & Oud Luxury", subtitle: "Powerful. Rich. Royal.", colorway: "arabic" },
  "gifts": { title: "Gift Collection", subtitle: "Premium. Elegant. Special.", colorway: "gift" },
  "best-sellers": { title: "Best Sellers", subtitle: "Loved across the MAHR circle.", colorway: "arabic" },
  "new-arrivals": { title: "New Arrivals", subtitle: "The latest from MAHR.", colorway: "unisex" }
};

if (typeof module !== "undefined") {
  module.exports = { MAHR_PRODUCTS, FILTER_OPTIONS, COLLECTIONS_META };
}
